/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "prueba2.h"
#include <time.h>

void
calculadora_prog_1(char *host,int a, int b)
{
	CLIENT *clnt;
	int  *result_1;
	operandos  suma_1_arg;
	suma_1_arg.a=a;
	suma_1_arg.b=b;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA_PROG, CALCULADORA_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = suma_1(&suma_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}
int sumar_local(int a, int b){
	return a+b;
}

int menu(){
	int opcion;
	printf("----------------------------------------\n" );
	printf("  1.- Sumar local\n" );
	printf("  2.- Sumar en la misma maquina 100000 veces\n" );
	printf("  3.- Sumar en distinta maquina 1000 veces\n");
	printf("  0.- Salir\n" );
	printf("----------------------------------------\n" );
	printf("  Opcion: ");
	scanf("%d",&opcion );
	printf("----------------------------------------\n" );
	return opcion;
}

int
main (int argc, char *argv[])
{
	char *host;
	int a,b,opcion=0,resultado;
	struct timeval t_ini,t_fin;
	double tiempo;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	do {
		opcion=menu();
		switch (opcion) {
			case 1:
			printf("  Introduce dos valores\n" );
			printf("  Primer valor: " );
			scanf("%d",&a );
			printf("  Segundo valor: " );
			scanf("%d",&b );
			gettimeofday(&t_ini,NULL);
			for(int i=0;i<100000;i++){
				resultado=sumar_local(a,b);
			}
			gettimeofday(&t_fin,NULL);
			tiempo=t_fin.tv_usec-t_ini.tv_usec;
			printf("  Tiempo en microsegundos: %d\n",(int)tiempo);
			break;
			case 2:
			printf("  Introduce dos valores\n" );
			printf("  Primer valor: " );
			scanf("%d",&a );
			printf("  Segundo valor: " );
			scanf("%d",&b );
			gettimeofday(&t_ini,NULL);
			for(int i=0;i<100000;i++){
				host="localhost";
				calculadora_prog_1(host,a,b);
			}
			gettimeofday(&t_fin,NULL);
			tiempo=(((t_fin.tv_sec-t_ini.tv_sec)*1000)+((t_fin.tv_usec-t_ini.tv_usec))/1000);
			tiempo=tiempo/1000;
			printf("  Tiempo empleado: %f\n",tiempo );
			break;
			case 3:
			printf("  Introduce dos valores\n" );
			printf("  Primer valor: " );
			scanf("%d",&a );
			printf("  Segundo valor: " );
			scanf("%d",&b );
			gettimeofday(&t_ini,NULL);
			for(int i=0;i<1000;i++){
				host = argv[1];
				calculadora_prog_1(host,a,b);
			}
			gettimeofday(&t_fin,NULL);
			tiempo=(((t_fin.tv_sec-t_ini.tv_sec)*1000)+((t_fin.tv_usec-t_ini.tv_usec))/1000);
			tiempo=tiempo/1000;
			printf("  Tiempo empleado: %f\n",tiempo );
			break;
			case 0:
				printf("  Saliendo...\n" );
			break;
			default:
			break;
		}
	} while(opcion!=0);

exit (0);
}
